-- Adicionar colunas de preços ao modelo User
ALTER TABLE users ADD COLUMN IF NOT EXISTS online_price FLOAT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS in_person_price FLOAT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS home_price FLOAT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS online_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS in_person_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS home_enabled BOOLEAN DEFAULT FALSE;
